# Generated by Django 4.2.15 on 2024-11-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferences',
            name='vault_token',
        ),
        migrations.AddField(
            model_name='preferences',
            name='site_type',
            field=models.CharField(choices=[('Staging', 'Staging'), ('Production', 'Production')], default='Staging', max_length=255),
        ),
    ]
