# Generated by Django 4.2.7 on 2024-07-09 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import geohosting.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Activity type.', max_length=256, unique=True)),
                ('jenkins_url', models.CharField(help_text='Jenkins URL based on identifier and product (optional).', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=256)),
                ('domain', models.CharField(blank=True, help_text='Domain url of the cluster', max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('order', models.PositiveIntegerField(default=0)),
                ('upstream_id', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('image', geohosting.models.fields.SVGAndImageField(blank=True, null=True, upload_to='product_images/')),
                ('available', models.BooleanField(default=False)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geohosting.cluster')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('data', models.JSONField()),
            ],
            options={
                'ordering': ('-triggered_at',),
            },
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_media/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='geohosting.product')),
            ],
            options={
                'ordering': ['product__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature_list', models.JSONField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package_code', models.CharField(help_text='This is the package code of the product on jenkins.', max_length=256)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='geohosting.product')),
            ],
            options={
                'ordering': ['product__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.cluster')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.package')),
            ],
            options={
                'unique_together': {('name', 'cluster')},
            },
        ),
        migrations.AddField(
            model_name='cluster',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.region'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('client_data', models.JSONField(blank=True, help_text='Data received from client.', null=True)),
                ('post_data', models.JSONField(blank=True, help_text='Data posted to jenkins.', null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'RUNNING'), ('BUILD_JENKINS', 'BUILD_JENKINS'), ('BUILD_ARGO', 'BUILD_ARGO'), ('ERROR', 'ERROR'), ('SUCCESS', 'SUCCESS')], default='RUNNING', help_text='The status of activity.', max_length=256)),
                ('note', models.TextField(blank=True, help_text='Note about activity.', null=True)),
                ('jenkins_queue_url', models.CharField(blank=True, max_length=256, null=True)),
                ('jenkins_build_url', models.CharField(blank=True, max_length=256, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.activitytype')),
                ('instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.instance')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ('-triggered_at',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together={('code', 'region')},
        ),
    ]
