# Generated by Django 4.2.7 on 2024-07-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmedia',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
