# Generated by Django 4.2.7 on 2024-07-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geohosting", "0002_pricing"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricing",
            options={"ordering": ["product__order", "order"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="productmedia",
            options={"ordering": ["product__order", "order"]},
        ),
        migrations.AddField(
            model_name="pricing",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productmedia",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
