# Generated by Django 4.2.7 on 2024-07-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0003_alter_pricing_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='features',
        ),
        migrations.AddField(
            model_name='pricing',
            name='feature_list',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
