# Generated by Django 4.2.7 on 2024-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0003_salesorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='currency',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='erpnext_code',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='package',
            name='erpnext_item_code',
            field=models.CharField(blank=True, default=''),
        ),
    ]
