# Generated by Django 4.2.7 on 2024-07-30 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geohosting.models.sales_order


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geohosting', '0004_package_currency_package_erpnext_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='delivery_date',
            field=models.DateTimeField(default=geohosting.models.sales_order.get_default_delivery_date, verbose_name='Delivery Date'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='erpnext_code',
            field=models.CharField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
