# Generated by Django 4.2.7 on 2024-08-01 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0005_salesorder_delivery_date_salesorder_erpnext_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='The key of metadata of product.', max_length=256)),
                ('value', models.TextField(help_text='Metadata value for the product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.product')),
            ],
            options={
                'unique_together': {('product', 'key')},
            },
        ),
    ]
