# Generated by Django 4.2.7 on 2024-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0006_productmetadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='periodicity',
            field=models.CharField(default='monthly', max_length=256),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Price id on the stripe.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Waiting Payment', 'Waiting Payment'), ('Paid', 'Paid')], default='Waiting Payment', help_text='The status of order.', max_length=256),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='stripe_id',
            field=models.CharField(blank=True, help_text='Checkout id on the stripe.', null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_code',
            field=models.CharField(blank=True, help_text='This is the package code of the product on jenkins.', max_length=256, null=True),
        ),
    ]
