# Generated by Django 4.2.7 on 2024-08-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0007_package_periodicity_package_stripe_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
