# Generated by Django 4.2.7 on 2024-08-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0009_ticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='paystack_id',
            field=models.CharField(blank=True, help_text='Price id on the paystack.', null=True),
        ),
        migrations.RenameField(
            model_name='salesorder',
            old_name='stripe_id',
            new_name='payment_id',
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='payment_id',
            field=models.CharField(blank=True, help_text='Checkout id on the payment gateway.', null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe'), ('Paystack', 'Paystack')], default='Stripe', help_text='The status of order.', max_length=256),
        ),
    ]
