# Generated by Django 4.2.15 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0010_rename_stripe_id_salesorder_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Feature Request', 'Feature Request'), ('Support', 'Support')], default='Support', max_length=15),
        ),
    ]
