# Generated by Django 4.2.15 on 2024-08-30 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0011_ticket_issue_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name that would be used for instance.It will also be used for sub domain.', null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Instance name just contains letter, number and dash')]),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='order_status',
            field=models.CharField(choices=[('Deployed', 'Deployed'), ('Waiting Configuration', 'Waiting Configuration'), ('Waiting Deployment', 'Waiting Deployment'), ('Waiting Payment', 'Waiting Payment')], default='Waiting Payment', help_text='The status of order.', max_length=256),
        ),
    ]
