# Generated by Django 4.2.15 on 2024-09-13 02:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import geohosting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0012_salesorder_app_name_alter_salesorder_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('package_code', models.CharField(blank=True, help_text='This is the package code of the product on jenkins.', max_length=256, null=True)),
                ('vault_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vault Config',
            },
        ),
        migrations.AlterModelOptions(
            name='activitytype',
            options={'verbose_name': 'Jenkins Activity Type'},
        ),
        migrations.RemoveField(
            model_name='package',
            name='package_code',
        ),
        migrations.AddField(
            model_name='activity',
            name='sales_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.salesorder'),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.product'),
        ),
        migrations.AddField(
            model_name='productcluster',
            name='environment',
            field=models.CharField(blank=True, help_text='The environment of the instance.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name that would be used for instance.It will also be used for sub domain.', null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Instance name just contains letter, number and dash'), geohosting.validators.app_name_validator]),
        ),
        migrations.CreateModel(
            name='ActivityTypeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geohosting_key', models.CharField(max_length=256)),
                ('jenkins_key', models.CharField(max_length=256)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.activitytype')),
            ],
        ),
        migrations.AddField(
            model_name='package',
            name='package_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.packagegroup'),
        ),
    ]
