# Generated by Django 4.2.15 on 2024-09-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0013_packagegroup_alter_activitytype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='packagegroup',
            options={},
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='identifier',
            field=models.CharField(help_text='Activity type.', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='activitytype',
            unique_together={('identifier', 'product')},
        ),
    ]
