# Generated by Django 4.2.15 on 2024-09-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0014_alter_packagegroup_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'RUNNING'), ('BUILD_ARGO', 'BUILD_ARGO'), ('ERROR', 'ERROR'), ('SUCCESS', 'SUCCESS')], default='RUNNING', help_text='The status of activity.', max_length=256),
        ),
    ]
