# Generated by Django 4.2.15 on 2024-09-20 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0015_webhookevent_note_alter_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='price_list',
            field=models.CharField(blank=True, default='', help_text='Selling price list of the package.'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='invoice',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
