# Generated by Django 4.2.15 on 2024-11-06 06:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0017_instance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpRequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT')])),
                ('data', models.JSONField(blank=True, null=True)),
                ('request_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Order Date')),
                ('response_code', models.IntegerField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
