# Generated by Django 4.2.15 on 2024-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0019_userprofile_avatar_userbillinginformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='erpnext_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='erpnext_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
