# Generated by Django 4.2.15 on 2024-11-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0020_ticket_erpnext_code_alter_salesorder_erpnext_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='jenkins_build_url',
        ),
    ]
