# Generated by Django 4.2.15 on 2024-11-20 09:21

import django.core.validators
from django.db import migrations, models
import geohosting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0022_alter_ticket_status_alter_ticket_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name that would be used for instance.It will also be used for sub domain.', null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9-]*$', 'Name may only contain letters, numbers or dashes.'), geohosting.validators.app_name_validator]),
        ),
    ]
