# Generated by Django 4.2.15 on 2024-11-20 10:33

import django.core.validators
from django.db import migrations, models
import geohosting.validators


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0023_alter_salesorder_app_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='app_name',
            field=models.CharField(blank=True, help_text='App name that would be used for instance.It will also be used for sub domain.', null=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]*$', 'Name may only contain lowercase letters, numbers or dashes.'), geohosting.validators.app_name_validator]),
        ),
    ]
