# Generated by Django 4.2.15 on 2024-11-21 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0025_country_remove_userbillinginformation_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillinginformation',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.country'),
        ),
    ]
