# Generated by Django 4.2.15 on 2024-11-22 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0027_company_companycontact_companybillinginformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='instance',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Keep blank if instance is for individual capacity..', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.company'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Keep blank if purchase for individual capacity..', null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
