# Generated by Django 4.2.15 on 2024-11-25 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0028_instance_company_salesorder_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erpnext_code', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=255)),
                ('default_currency', models.CharField(blank=True, max_length=256, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payment_method', models.CharField(choices=[('Stripe', 'Stripe'), ('Paystack', 'Paystack')], default='Stripe', help_text='The status of order.', max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Erp Companies',
                'ordering': ('name',),
            },
        ),
    ]
