# Generated by Django 4.2.15 on 2024-11-26 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0029_erpcompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='AgreementDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('version', models.IntegerField(default=1, help_text='The highest version will be used')),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.agreement')),
            ],
            options={
                'ordering': ('agreement__name', '-version'),
                'unique_together': {('agreement', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SalesOrderAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('agreement_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.agreementdetail')),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geohosting.salesorder')),
            ],
            options={
                'unique_together': {('sales_order', 'agreement_detail')},
            },
        ),
    ]
