# Generated by Django 4.2.15 on 2024-12-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0031_salesorderagreement_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Deploying', 'Deploying'), ('Starting Up', 'Starting Up'), ('Online', 'Online'), ('Offline', 'Offline')], default='Deploying'),
        ),
    ]
