# Generated by Django 4.2.15 on 2025-03-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0032_alter_instance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderagreement',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='agreements/'),
        ),
    ]
