# Generated by Django 4.2.15 on 2025-03-14 02:18

from django.db import migrations, models
import django.db.models.deletion
from geohosting.models.activity import Activity


def run(apps, schema_editor):
    for activity in Activity.objects.all():
        activity.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0034_logtracker'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='instance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instance',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='instance',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geohosting.instance'),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Deploying', 'Deploying'), ('Starting Up', 'Starting Up'), ('Online', 'Online'), ('Offline', 'Offline'), ('Terminating', 'Terminating'), ('Terminated', 'Terminated')], default='Deploying'),
        ),
        migrations.RunPython(run, migrations.RunPython.noop),
    ]
