# Generated by Django 4.2.15 on 2025-03-21 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geohosting', '0036_alter_instance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geohosting.activity'),
        ),
        migrations.AddField(
            model_name='webhookevent',
            name='app_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='instance',
            name='status',
            field=models.CharField(choices=[('Deploying', 'Deploying'), ('Starting Up', 'Starting Up'), ('Online', 'Online'), ('Offline', 'Offline'), ('Deleting', 'Deleting'), ('Deleted', 'Deleted')], db_index=True, default='Deploying'),
        ),
    ]
